import React from "react"
import img1 from '../BMW 4 series.jpeg';
import img2 from '../toypta supra.jpeg';
import img3 from '../toypta supra.jpeg';
import img4 from '../toypta supra.jpeg';
import img5 from '../toypta supra.jpeg';
import img6 from '../toypta supra.jpeg';
import img7 from '../toypta supra.jpeg';
import img8 from '../toypta supra.jpeg';
import img9 from '../toypta supra.jpeg';
import img10 from '../toypta supra.jpeg';
import img11 from '../toypta supra.jpeg';
import img12 from '../toypta supra.jpeg';
import img13 from '../toypta supra.jpeg';
import img14 from '../toypta supra.jpeg';
import img15 from '../toypta supra.jpeg';
import img16 from '../toypta supra.jpeg';
import img17 from '../toypta supra.jpeg';
import img18 from '../toypta supra.jpeg';
import img19 from '../toypta supra.jpeg';
import img20 from '../toypta supra.jpeg';
import img21 from '../toypta supra.jpeg';
import img22 from '../toypta supra.jpeg';
import img23 from '../toypta supra.jpeg';
import img24 from '../toypta supra.jpeg';
import img25 from '../toypta supra.jpeg';
import img26 from '../toypta supra.jpeg';
import img27 from '../toypta supra.jpeg';
import img28 from '../toypta supra.jpeg';
import img29 from '../toypta supra.jpeg';
import img30 from '../toypta supra.jpeg';
import img31 from '../toypta supra.jpeg';
import img32 from '../toypta supra.jpeg';
import img33 from '../toypta supra.jpeg';
import img34 from '../toypta supra.jpeg';
import img35 from '../toypta supra.jpeg';
import img36 from '../toypta supra.jpeg';
import img37 from '../toypta supra.jpeg';
import img38 from '../toypta supra.jpeg';
import img39 from '../toypta supra.jpeg';
import img40 from '../toypta supra.jpeg';
import img41 from '../toypta supra.jpeg';
import img42 from '../toypta supra.jpeg';
import img43 from '../toypta supra.jpeg';
import img44 from '../toypta supra.jpeg';
import img45 from '../toypta supra.jpeg';
import img46 from '../toypta supra.jpeg';
import img47 from '../toypta supra.jpeg';
import img48 from '../toypta supra.jpeg';
import img49 from '../toypta supra.jpeg';
import img50 from '../toypta supra.jpeg';
import img51 from '../toypta supra.jpeg';
import img52 from '../toypta supra.jpeg';
import img53 from '../toypta supra.jpeg';
import img54 from '../toypta supra.jpeg';
import img55 from '../toypta supra.jpeg';
import img56 from '../toypta supra.jpeg';
import img57 from '../toypta supra.jpeg';
import img58 from '../toypta supra.jpeg';
import img59 from '../toypta supra.jpeg';
import img60 from '../toypta supra.jpeg';

    let data=[
      {
        id: 1,
        car_name: "BMW 4 series",
        image: img1,
        range: 4,
        type: "Hybrid",
        speed: "7.2km/1-Litre",
        service: "Automatic",
        EMI: "$430/month",
      },
      {
        id: 2,
        car_name: "Toyota Supra",
        image: img2,
        range: 4,
        type: "Hybrid",
        speed: "6.1km/1-Litre",
        service: "Automatic",
        EMI: "$440/month",

      },
      {
        id: 3,
        car_name: "BMW 3 series",
        image: img3,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 4,
        car_name: "Volkwagen T-Cross",
        image: img4,
        range: 4,
        type: "Gasoline",
        speed: "5.3km/1-Litre",
        service: "Automatic",
        EMI: "$400/month",
      },
      {
        id: 5,
        car_name:"BMW 4 Series GTI",
        image: img5,
        range: 4,
        type: "Gasoline",
        speed: "7.6km/1-Litre",
        service: "Automatic",
        EMI: "$530/month",
      },
      {
        id: 6,
        car_name: "Cadillac Escalade",
        image: img6,
        range: 4,
        type: "Gasoline",
        speed: "7.7km/1-Litre",
        service: "Automatic",
        EMI: "$620/month",
      },
      {
        id: 7,
        car_name: "Celica",
        image: img7,
        range: 4,
        type: "Hybrid",
        speed: "8.0km/1-Litre",
        service: "Automatic",
        EMI: "$320/month",
      },
      {
        id: 8,
        car_name: "Ford Probe",
        image: img8,
        range: 2,
        type: "Gasoline",
        speed: "6.2km/1-Litre",
        service:"Automatic",
        EMI: "$550/month",
      },
      {
        id: 9,
        car_name: "Buggati",
        image: img9,
        range: 2,
        type: "Hybrid",
        speed: "8.7km/1-Litre",
        service: "Automatic",
        EMI: "$550/month",
      },
      {
        id: 10,
        car_name: "Chevy",
        image: img10,
        range: 4,
        type: "Diesel",
        speed: "6.0km/1-Litre",
        service: "Automatic",
        EMI: "$300/month",
      },
      {
        id: 11,
        car_name: "Dodge Wipers",
        image: img11,
        range: 2,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$650/month",
      },
      {
        id: 12,
        car_name:"Ferrari Enzo",
        image: img12,
        range: 4,
        type: "Hybrid",
        speed:"9.0km / 1-Litre",
        service: "Automatic",
        EMI: "$400/month",
      },{
        id: 13,
        car_name: "Ferrari",
        image: img13,
        range: 1,
        type: "Hybrid",
        speed: "7.4km/1-Litre",
        service:" Automatic",
        EMI: "$700/month",
      },
      {
        id: 14,
        car_name: "Ford Mustang",
        image: img14,
        range: 4,
        type: "Gasoline",
        speed:"7.2km/1-Litre",
        service: "Automatic",
        EMI: "$250/month",
      },
      {
        id: 15,
        car_name: "Kia",
        image: img15,
        range: 4,
        type:" Hybrid",
        speed: "8.5km/1-Litre",
        service: "Automatic",
        EMI: "$500/month",
      },
      {
        id: 16,
        car_name: "Mercedees",
        image: img16,
        range: 1,
        type: "Gasoline",
        speed: "9.2km/1-Litre",
        service: "Automatic",
        EMI: "$700/month",
      },
      {
        id: 17,
        car_name: "Porche",
        image: img17,
        range: 2,
        type: "Gasoline",
        speed: "8.0km/1-Litre",
        service: "Automatic",
        EMI: "$750/month",
      },{
        id: 18,
        car_name: "Renault Tiger",
        image: img18,
        range: 4,
        type: "Hybrid",
        speed: "7.7km/1-Litre",
        service: "Automatic",
        EMI: "$450/month",
      },
      {
        id: 19,
        car_name: "Subaru",
        image: img19,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 20,
        car_name: "Tata Azura",
        image: img20,
        range: 4,
        type: "Hybrid",
        speed: "6.6km/1-Litre",
        service: "Automatic",
        EMI: "$300/month",
      },
      {
        id: 21,
        car_name: "Volkswagen",
        image: img21,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 22,
        car_name: "Volkswagen",
        image: img22,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 23,
        car_name: "Volkswagen",
        image: img23,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 24,
        car_name: "Volkswagen",
        image: img24,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 25,
        car_name: "Volkswagen",
        image: img25,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 26,
        car_name: "Volkswagen",
        image: img26,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 27,
        car_name: "Volkswagen",
        image: img27,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 28,
        car_name: "Volkswagen",
        image: img28,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 29,
        car_name: "Volkswagen",
        image: img29,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 30,
        car_name: "Volkswagen",
        image: img30,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 31,
        car_name: "Volkswagen",
        image: img31,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 32,
        car_name: "Volkswagen",
        image: img32,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 33,
        car_name: "Volkswagen",
        image: img33,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 34,
        car_name: "Volkswagen",
        image: img34,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 35,
        car_name: "Volkswagen",
        image: img35,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 36,
        car_name: "Volkswagen",
        image: img36,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 37,
        car_name: "Volkswagen",
        image: img37,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 38,
        car_name: "Volkswagen",
        image: img38,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 39,
        car_name: "Volkswagen",
        image: img39,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 40,
        car_name: "Volkswagen",
        image: img40,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 41,
        car_name: "Volkswagen",
        image: img41,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 42,
        car_name: "Volkswagen",
        image: img42,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 43,
        car_name: "Volkswagen",
        image: img43,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 44,
        car_name: "Volkswagen",
        image: img44,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 45,
        car_name: "Volkswagen",
        image: img45,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 46,
        car_name: "Volkswagen",
        image: img46,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 47,
        car_name: "Volkswagen",
        image: img47,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 48,
        car_name: "Volkswagen",
        image: img48,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 49,
        car_name: "Volkswagen",
        image: img49,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 50,
        car_name: "Volkswagen",
        image: img50,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 51,
        car_name: "Volkswagen",
        image: img51,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 52,
        car_name: "Volkswagen",
        image: img52,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 53,
        car_name: "Volkswagen",
        image: img53,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 54,
        car_name: "Volkswagen",
        image: img54,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 55,
        car_name: "Volkswagen",
        image: img55,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 56,
        car_name: "Volkswagen",
        image: img56,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 57,
        car_name: "Volkswagen",
        image: img57,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 58,
        car_name: "Volkswagen",
        image: img58,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 59,
        car_name: "Volkswagen",
        image: img59,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 60,
        car_name: "Volkswagen",
        image: img60,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      
    ]

// export default Car;