
const img1='https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Bugatti_Chiron_1.jpg/1200px-Bugatti_Chiron_1.jpg';
const img2="https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/2021_Ferrari_F8_Tributo.jpg/1280px-2021_Ferrari_F8_Tributo.jpg"

    let data=[
      {
        id: 1,
        car_name: "BMW 4 series",
        page:"1",
        image: img1,
        range: 4,
        type: "Hybrid",
        speed: "7.2km/1-Litre",
        service: "Automatic",
        EMI: "$430/month",
      },
      {
        id: 2,
        car_name: "Toyota Supra",
        page:"1",
        image: img2,
        range: 4,
        type: "Hybrid",
        speed: "6.1km/1-Litre",
        service: "Automatic",
        EMI: "$440/month",

      },
      {
        id: 3,
        car_name: "BMW 3 series",
        page:"1",
        image: img1,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 4,
        car_name: "Volkwagen T-Cross",
        page:"1",
        image: img2,
        range: 4,
        type: "Gasoline",
        speed: "5.3km/1-Litre",
        service: "Automatic",
        EMI: "$400/month",
      },
      {
        id: 5,
        car_name:"BMW 4 Series GTI",
        page:"1",
        image: img1,
        range: 4,
        type: "Gasoline",
        speed: "7.6km/1-Litre",
        service: "Automatic",
        EMI: "$530/month",
      },
      {
        id: 6,
        car_name: "Cadillac Escalade",
        page:"1",
        image: img2,
        range: 4,
        type: "Gasoline",
        speed: "7.7km/1-Litre",
        service: "Automatic",
        EMI: "$620/month",
      },
      {
        id: 7,
        car_name: "Celica",
        page:"2",
        image: img1,
        range: 4,
        type: "Hybrid",
        speed: "8.0km/1-Litre",
        service: "Automatic",
        EMI: "$320/month",
      },
      {
        id: 8,
        car_name: "Ford Probe",
        page:"2",
        image: img2,
        range: 2,
        type: "Gasoline",
        speed: "6.2km/1-Litre",
        service:"Automatic",
        EMI: "$550/month",
      },
      {
        id: 9,
        car_name: "Buggati",
        page:"2",
        image: img1,
        range: 2,
        type: "Hybrid",
        speed: "8.7km/1-Litre",
        service: "Automatic",
        EMI: "$550/month",
      },
      {
        id: 10,
        car_name: "Chevy",
        page:"2",
        image: img2,
        range: 4,
        type: "Diesel",
        speed: "6.0km/1-Litre",
        service: "Automatic",
        EMI: "$300/month",
      },
      {
        id: 11,
        car_name: "Dodge Wipers",
        page:"2",
        image: img1,
        range: 2,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$650/month",
      },
      {
        id: 12,
        car_name:"Ferrari Enzo",
        page:"2",
        image: img2,
        range: 4,
        type: "Hybrid",
        speed:"9.0km / 1-Litre",
        service: "Automatic",
        EMI: "$400/month",
      },{
        id: 13,
        car_name: "Ferrari",
        page:"3",
        image: img1,
        range: 1,
        type: "Hybrid",
        speed: "7.4km/1-Litre",
        service:" Automatic",
        EMI: "$700/month",
      },
      {
        id: 14,
        car_name: "Ford Mustang",
        page:"3",
        image: img2,
        range: 4,
        type: "Gasoline",
        speed:"7.2km/1-Litre",
        service: "Automatic",
        EMI: "$250/month",
      },
      {
        id: 15,
        car_name: "Kia",
        page:"3",
        image: img1,
        range: 4,
        type:" Hybrid",
        speed: "8.5km/1-Litre",
        service: "Automatic",
        EMI: "$500/month",
      },
      {
        id: 16,
        car_name: "Mercedees",
        page:"3",
        image: img2,
        range: 1,
        type: "Gasoline",
        speed: "9.2km/1-Litre",
        service: "Automatic",
        EMI: "$700/month",
      },
      {
        id: 17,
        car_name: "Porche",
        page:"3",
        image: img1,
        range: 2,
        type: "Gasoline",
        speed: "8.0km/1-Litre",
        service: "Automatic",
        EMI: "$750/month",
      },{
        id: 18,
        car_name: "Renault Tiger",
        page:"3",
        image: img2,
        range: 4,
        type: "Hybrid",
        speed: "7.7km/1-Litre",
        service: "Automatic",
        EMI: "$450/month",
      },
      {
        id: 19,
        car_name: "Subaru",
        image: img1,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 20,
        car_name: "Tata Azura",
        image: img2,
        range: 4,
        type: "Hybrid",
        speed: "6.6km/1-Litre",
        service: "Automatic",
        EMI: "$300/month",
      },
      {
        id: 21,
        car_name: "Volkswagen",
        image: img1,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 22,
        car_name: "Volkswagen",
        image: img2,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 23,
        car_name: "Volkswagen",
        image: img1,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 24,
        car_name: "Volkswagen",
        image: img2,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 25,
        car_name: "Volkswagen",
        image: img1,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 26,
        car_name: "Volkswagen",
        image: img2,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 27,
        car_name: "Volkswagen",
        image: img1,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 28,
        car_name: "Volkswagen",
        image: img2,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 29,
        car_name: "Volkswagen",
        image: img1,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 30,
        car_name: "Volkswagen",
        image: img2,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 31,
        car_name: "Volkswagen",
        image: img1,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 32,
        car_name: "Volkswagen",
        image: img2,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 33,
        car_name: "Volkswagen",
        image: img1,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 34,
        car_name: "Volkswagen",
        image: img2,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 35,
        car_name: "Volkswagen",
        image: img1,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 36,
        car_name: "Volkswagen",
        image: img2,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 37,
        car_name: "Volkswagen",
        image: img1,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 38,
        car_name: "Volkswagen",
        image: img2,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 39,
        car_name: "Volkswagen",
        image: img1,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 40,
        car_name: "Volkswagen",
        image: img2,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 41,
        car_name: "Volkswagen",
        image: img1,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 42,
        car_name: "Volkswagen",
        image: img2,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 43,
        car_name: "Volkswagen",
        image: img1,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 44,
        car_name: "Volkswagen",
        image: img2,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 45,
        car_name: "Volkswagen",
        image: img1,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 46,
        car_name: "Volkswagen",
        image: img2,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 47,
        car_name: "Volkswagen",
        image: img1,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 48,
        car_name: "Volkswagen",
        image: img2,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 49,
        car_name: "Volkswagen",
        image: img1,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 50,
        car_name: "Volkswagen",
        image: img2,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 51,
        car_name: "Volkswagen",
        image: img1,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 52,
        car_name: "Volkswagen",
        image: img2,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 53,
        car_name: "Volkswagen",
        image: img1,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 54,
        car_name: "Volkswagen",
        image: img2,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 55,
        car_name: "Volkswagen",
        image: img1,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 56,
        car_name: "Volkswagen",
        image: img2,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 57,
        car_name: "Volkswagen",
        image: img1,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 58,
        car_name: "Volkswagen",
        image: img2,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 59,
        car_name: "Volkswagen",
        image: img1,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      {
        id: 60,
        car_name: "Volkswagen",
        image: img2,
        range: 4,
        type: "Gasoline",
        speed: "8.2km/1-Litre",
        service: "Automatic",
        EMI: "$350/month",
      },
      
    ]

export default data;